spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/OnlineBanking
    username: root
    password: mysql
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

